### ISSUE TITLE
Doesn't create timestamp for RDS snapshots

### ISSUE THREAD

**Issue by mtmdeploy** [xombiemp/rds-copy-snapshots-lambda#1]
Unable to run on a daily basis or create multiple snapshots as it doesn't appear to be able to actually create a timestamp for a snapshot. Any ideas? Thanks!

An error occurred (DBSnapshotAlreadyExists) when calling the CopyDBSnapshot operation: Cannot create the snapshot because a snapshot with the identifier <identifier name> already exists.: DBSnapshotAlreadyExistsFault
Traceback (most recent call last):
File "/var/task/rds-copy-snapshots.py", line 113, in main
copy_snapshots(rds, snapshots_auto)
File "/var/task/rds-copy-snapshots.py", line 20, in copy_snapshots
TargetDBSnapshotIdentifier=newest['DBSnapshotIdentifier'][4:]
File "/var/runtime/botocore/client.py", line 253, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 543, in _make_api_call
raise error_class(parsed_response, operation_name)
DBSnapshotAlreadyExistsFault: An error occurred (DBSnapshotAlreadyExists) when calling the CopyDBSnapshot operation: Cannot create the snapshot because a snapshot with the identifier <identifier name> already exists.

**Comment by xombiemp** [comment]
It was designed to run on a monthly basis, because RDS can be configured to allow point-in-time recovery for up to 30 something days.  So just schedule this function to run once a month to keep a monthly archival backup.
